server:
  port: 8091
  tomcat:
    max-threads: 10
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0  #采样百分比 0-1
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 9999
        dashboard: localhost:8888

#service-product: #调用的提供者名称
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  sentinel:
    enabled: true
rocketmq:
  name-server: 192.168.56.105:9876
  producer:
    group: shop-order