server:
  port: 7000
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0  #采样百分比 0-1
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
       - id: product_route
         uri: lb://service-product   #负载均衡+微服务具体标识
         order: 1
         predicates:
           - Path=/product-serv/**
#           - Age=18,60
#           - Before=2010-12-24T00:00:00.000+08:00
#           - Method=post
         filters:
           - StripPrefix=1  #http://localhost:7000/product-serv/product/1
       - id: order_route
         uri: lb://service-order   #负载均衡+微服务具体标识
         order: 1
         predicates:
           - Path=/order-serv/**
         filters:
           - StripPrefix=1  #http://localhost:7000/product-serv/product/1
#           - Log=true,false
#           - SetStatus=250

      discovery:
        locator:
          enabled: true  #从gateway获取信息
